In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
sheet = pd.ExcelFile('Analysis_Sheet.xlsx')

In [21]:
print(sheet.sheet_names)

['Sheet1', 'avg_day', 'period', 'weekday', 'hours', 'count_id_per_period', 'total_per_day', 'count_per_hour', 'الفتره']

In [22]:
print(sheet.sheet_names[0])

Sheet1

In [23]:
df = sheet.parse(0)

In [26]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df.head(-5)

,ID_shift,DateTime,TotalCost,OrderDate,Weekday,Hour,Period,ID,Hours
0,1.0,2025-06-02 18:33:06,165,2025-06-02,الإثنين,18.0,مساء,1.0,6 PM
1,2.0,2025-06-02 18:33:20,75,2025-06-02,الإثنين,18.0,مساء,2.0,6 PM
2,3.0,2025-06-02 18:36:40,70,2025-06-02,الإثنين,18.0,مساء,3.0,6 PM
3,4.0,2025-06-02 18:40:40,10,2025-06-02,الإثنين,18.0,مساء,4.0,6 PM
4,5.0,2025-06-02 18:40:44,60,2025-06-02,الإثنين,18.0,مساء,5.0,6 PM
...,...,...,...,...,...,...,...,...,...
450,5.0,2025-07-08 11:12:38,80,2025-07-08,الثلاثاء,11.0,صباحا,451.0,11 AM
451,6.0,2025-07-08 12:12:30,20,2025-07-08,الثلاثاء,12.0,ظهرا,452.0,12 PM
452,7.0,2025-07-08 12:15:52,60,2025-07-08,الثلاثاء,12.0,ظهرا,453.0,12 PM
453,8.0,2025-07-08 12:19:23,20,2025-07-08,الثلاثاء,12.0,ظهرا,454.0,12 PM
454,9.0,2025-07-08 12:19:28,80,2025-07-08,الثلاثاء,12.0,ظهرا,455.0,12 PM

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID_shift   455 non-null    float64
 1   DateTime   455 non-null    datetime64[ns]
 2   TotalCost  457 non-null    object
 3   OrderDate  455 non-null    datetime64[ns]
 4   Weekday    455 non-null    object
 5   Hour       455 non-null    float64
 6   Period     455 non-null    object
 7   ID         455 non-null    float64
 8   Hours      455 non-null    object
dtypes: datetime64[ns](2), float64(3), object(4)
memory usage: 32.5+ KB

In [33]:
df.describe()

,ID_shift,DateTime,OrderDate,Hour,ID
count,455.000000,455,455,455.000000,455.000000
mean,22.637363,2025-06-25 11:57:43.169230592,2025-06-24 21:21:45.494505472,14.065934,228.000000
min,1.000000,2025-06-02 18:33:06,2025-06-02 00:00:00,0.000000,1.000000
25%,5.000000,2025-06-13 21:50:15,2025-06-13 00:00:00,12.000000,114.500000
50%,13.000000,2025-07-02 12:46:26,2025-07-02 00:00:00,16.000000,228.000000
75%,28.000000,2025-07-03 18:52:11.500000,2025-07-03 00:00:00,18.000000,341.500000
max,111.000000,2025-07-08 12:19:28,2025-07-08 00:00:00,23.000000,455.000000
std,26.166494,NaN,NaN,5.927614,131.491445

In [55]:
df.head(5)

,ID_shift,DateTime,TotalCost,OrderDate,Weekday,Hour,Period,ID,Hours
0,1.0,2025-06-02 18:33:06,165,2025-06-02,الإثنين,18.0,مساء,1.0,6 PM
1,2.0,2025-06-02 18:33:20,75,2025-06-02,الإثنين,18.0,مساء,2.0,6 PM
2,3.0,2025-06-02 18:36:40,70,2025-06-02,الإثنين,18.0,مساء,3.0,6 PM
3,4.0,2025-06-02 18:40:40,10,2025-06-02,الإثنين,18.0,مساء,4.0,6 PM
4,5.0,2025-06-02 18:40:44,60,2025-06-02,الإثنين,18.0,مساء,5.0,6 PM

In [56]:
df['OrderDate'].corr(df['ID']) # correlation between two var

0.9237040829123344